**Module 3: Data Structures Assignments**

Assignment 1:

 Creating and Accessing Lists
Create a list of the first 20 positive integers. Print the list.

In [3]:
list1=list(range(1,21))
print(list1)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]

Assignment 2: Accessing List Elements

Print the first, middle, and last elements of the list created in Assignment 1.

In [5]:
print("first element: ",list1[0])
print("middle element: ",len(list1)//2)
print("last element: ",list1[-1])

first element:  1
middle element:  10
last element:  20

Assignment 3: List Slicing
Print the first five elements, the last five elements, and the elements from index 5 to 15 of the list created in Assignment 1.

In [12]:
print(list1[:5])
print(list1[-5:])
print(list1[5:15])

[1, 2, 3, 4, 5]
[16, 17, 18, 19, 20]
[6, 7, 8, 9, 10, 11, 12, 13, 14, 15]

Assignment 4: List Comprehensions
Create a new list containing the squares of the first 10 positive integers using a list comprehension. Print the new list.

In [13]:
list2=[i**2 for i in range(1,11)]
print(list2)

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]

Assignment 5: Filtering Lists
Create a new list containing only the even numbers from the list created in Assignment 1 using a list comprehension. Print the new list.

In [15]:
list3=[i for i in range(1,21) if i%2==0]
print(list3)

[2, 4, 6, 8, 10, 12, 14, 16, 18, 20]

Assignment 6: List Methods
Create a list of random numbers and sort it in ascending and descending order. Remove the duplicates from the list and print the modified list.

In [20]:
list4=[23,255,435,34,53534,234,34,23]
print(sorted(list4))
print(sorted(list4,reverse=True))
print(set(list4))

[23, 23, 34, 34, 234, 255, 435, 53534]
[53534, 435, 255, 234, 34, 34, 23, 23]
{34, 234, 435, 23, 53534, 255}

Assignment 7: Nested Lists
Create a nested list representing a 3x3 matrix and print the matrix. Access and print the element at the second row and third column.

In [23]:
nested_list=[[1,2,3],[4,5,6],[7,8,9]]
for i in nested_list:
  print(i)
print(nested_list[1][2])

[1, 2, 3]
[4, 5, 6]
[7, 8, 9]
6

Assignment 8: List of Dictionaries
Create a list of dictionaries where each dictionary represents a student with keys 'name' and 'score'. Sort the list of dictionaries by the 'score' in descending order and print the sorted list.

In [25]:
student=[{"name":"Nikhil","Score":85},{"name":"Thoutam","Score":75}]
sorted_list=sorted(student,key=lambda x:x["Score"],reverse=True)
print(sorted_list)

[{'name': 'Nikhil', 'Score': 85}, {'name': 'Thoutam', 'Score': 75}]

9: Matrix Transposition
Write a function that takes a 3x3 matrix (nested list) as input and returns its transpose. Print the original and transposed matrices.

In [28]:
def transpose_matrix(matrix):
    transposed=[]
    for i in range(len(matrix[0])):
        transposed_row=[]
        for row in matrix:
            transposed_row.append(row[i])
        transposed.append(transposed_row)
    return transposed


matrix=[[1,2,3],[4,5,6],[7,8,9]]
print(transpose_matrix(matrix))

[[1, 4, 7], [2, 5, 8], [3, 6, 9]]

Assignment 10: Flattening a Nested List
Write a function that takes a nested list and flattens it into a single list. Print the original and flattened lists.

Assignment 11: List Manipulation
Create a list of the first 10 positive integers. Remove the elements at indices 2, 4, and 6, and insert the element '99' at index 5. Print the modified list.

In [39]:
list1=list(range(1,11))
print(list1.pop(2))
print(list1.pop(6))
print(list1.pop(4))
(list1.insert(5,99))
print(list1)

3
8
6
None
[1, 2, 4, 5, 7, 99, 9, 10]

Assignment 12: List Zipping
Create two lists of the same length. Use the zip function to combine these lists into a list of tuples and print the result.

In [40]:
list1=[1,2,3,4,5]
list2=[6,7,8,9,10]
print(list(zip(list1,list2)))

[(1, 6), (2, 7), (3, 8), (4, 9), (5, 10)]

Assignment 13: List Reversal
Write a function that takes a list and returns a new list with the elements in reverse order. Print the original and reversed lists.

In [42]:
def reverse_list(list1):
    return list1[::-1]
list1=[1,2,3,4,5]
print(list1)
print(reverse_list(list1))

[1, 2, 3, 4, 5]
[5, 4, 3, 2, 1]

Assignment 14: List Rotation
Write a function that rotates a list by n positions. Print the original and rotated lists.

In [43]:
def rotate_list(list1,n):
    return list1[n:]+list1[:n]
list1=[1,2,3,4,5]
print(list1)
print(rotate_list(list1,2))

[1, 2, 3, 4, 5]
[3, 4, 5, 1, 2]

Assignment 15: List Intersection
Write a function that takes two lists and returns a new list containing only the elements that are present in both lists. Print the intersected list.

In [44]:
def intersection_kist(list1,list2):
  return list(set(list1).intersection(set(list2)))
list1=[1,2,3,4,5]
list2=[4,5,6,7,8]
print(intersection_kist(list1,list2))

[4, 5]