Module 3: Data Structures Assignments
Lesson 3.3: Sets

Assignment 1: Creating and Accessing Sets
Create a set with the first 10 positive integers. Print the set.

In [ ]:
set1=set(range(1,11))
print(set1)

{1, 2, 3, 4, 5, 6, 7, 8, 9, 10}

Assignment 2: Adding and Removing Elements
Add the number 11 to the set created in Assignment 1. Then remove the number 1 from the set. Print the modified set.

In [ ]:
set1.add(11)
set1.remove(1)
print(set1)

{2, 3, 4, 5, 6, 7, 8, 9, 10, 11}

Assignment 3: Set Operations
Create two sets: one with the first 5 positive integers and another with the first 5 even integers. Perform and print the results of union, intersection, difference, and symmetric difference operations on these sets.

In [ ]:
set1={1,2,3,4,5}
set2={2,4,6,8,10}
print(set1.union(set2))
print(set1.symmetric_difference(set2))
print(set1.difference(set2))

{1, 2, 3, 4, 5, 6, 8, 10}
{1, 3, 5, 6, 8, 10}
{1, 3, 5}

Assignment 4: Set Comprehensions
Create a new set containing the squares of the first 10 positive integers using a set comprehension. Print the new set.

In [ ]:
set1={i**2 for i in range(1,11)}
print(set1)

{64, 1, 4, 36, 100, 9, 16, 49, 81, 25}

Assignment 5: Filtering Sets
Create a new set containing only the even numbers from the set created in Assignment 1 using a set comprehension. Print the new set.

In [ ]:
set1={1,2,3,4,5,6,7,8,9,10}
set2={i for i in set1 if i%2==0}
print(set2)

{2, 4, 6, 8, 10}

Assignment 6: Set Methods
Create a set with duplicate elements and remove the duplicates using set methods. Print the modified set.

In [ ]:
step={1,1,2,2,3,4,5,6,6,7,43,34,34,34,43}
print(step)

{1, 2, 3, 4, 5, 6, 7, 34, 43}

Assignment 7: Subsets and Supersets
Create two sets: one with the first 5 positive integers and another with the first 3 positive integers. Check if the second set is a subset of the first set and if the first set is a superset of the second set. Print the results.

In [ ]:
set1={1,2,3,4,5}
set2={1,2,3}
set3=set2.issubset(set1)
if set1.issuperset(set2):
    print("set2 is a subset of set1")
else:
    print("set2 is not a subset of set1")
print(set3)

set2 is a subset of set1
True

Assignment 8: Frozenset
Create a frozenset with the first 5 positive integers. Print the frozenset.

In [ ]:
frozenset1=frozenset(range(1,6))
print(frozenset1)

frozenset({1, 2, 3, 4, 5})

Assignment 9: Set and List Conversion
Create a set with the first 5 positive integers. Convert it to a list, append the number 6, and convert it back to a set. Print the resulting set.

In [ ]:
set1={1,2,3,4,5}
list1=list(set1)
list1.append(6)
set2=set(list1)
print(set2)

{1, 2, 3, 4, 5, 6}

Assignment 10: Set and Dictionary
Create a dictionary with set keys and integer values. Print the dictionary.

In [2]:
dict1={frozenset({1,2,3}):10,frozenset({4,5,6}):20}
print(dict1)

{frozenset({1, 2, 3}): 10, frozenset({4, 5, 6}): 20}

Assignment 11: Iterating Over Sets
Create a set and iterate over the elements, printing each element.

In [4]:
set1={1,2,3,4,5}
for i in set1:
  print(i)

1
2
3
4
5

Assignment 12: Removing Elements from Sets
Create a set and remove elements from it until it is empty. Print the set after each removal.

In [5]:
set1={1,2,3,4,5}
while set1:
  set1.pop()
  print(set1)

{2, 3, 4, 5}
{3, 4, 5}
{4, 5}
{5}
set()

Assignment 13: Set Symmetric Difference Update
Create two sets and update the first set with the symmetric difference of the two sets. Print the modified first set.

In [6]:
set1={1,2,3,4,5}
set2={4,5,6,7,8}
set3=set1.symmetric_difference(set2)
set1=set3
print(set1)

{1, 2, 3, 6, 7, 8}

Assignment 14: Set Membership Testing
Create a set and test if certain elements are present in the set. Print the results.

In [7]:
set1={1,2,3,4,5,5,6,7,7,77,83,4,435,34,435,43}
n=int(input("enter the number you want to check"))
present_or_not=n in set1
print(present_or_not)

enter the number you want to check55
False

Assignment 15: Set of Tuples
Create a set containing tuples, where each tuple contains two elements. Print the set.

In [8]:
set1={(1,2),(3,4),(5,6)}
print(set1)

{(1, 2), (3, 4), (5, 6)}